export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const PRE_FLIGHT_STATUS = 'PRE_FLIGHT_STATUS'
export const POST_FLIGHT_STATUS = 'POST_FLIGHT_STATUS'
